name: Extract Bioschemas

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths:
      - '*.groovy'

jobs:
  bioschemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install groovy
        run: sudo apt install groovy

      - name: Extract Bioschemas
        run: |
          groovy extractBioschemas.groovy | tee cloud.ttl

      - name: Commit Turtle
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add *.ttl
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Extracted new Bioschemas data as Turtle'
              git push
          fi

      - name: RDF syntax check
        uses: AtomGraph/RDF-syntax-check@v1.0.4
